# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/54683f1a-0dee-43fe-8dd4-c9d0dba650e4";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-bf68648d-b64e-4931-b0b7-3631ed1adb71".device = "/dev/disk/by-uuid/bf68648d-b64e-4931-b0b7-3631ed1adb71";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/AD2D-C808";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  # /nix is stored on a different drive
  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/8b3479d8-87f2-4976-ba41-66a303447738";
    fsType = "ext4";
    neededForBoot = true;
    options = ["noatime"];
  };

  swapDevices = [];

  fileSystems."/home/tim/Share" = {
    device = "/dev/disk/by-partuuid/c13ec39c-cedf-445b-a405-92b52d5530b8";
    fsType = "ntfs-3g";
    options = ["rw" "umask=022" "uid=1000" "gid=100"];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
